'use client';

import { useMemo, useState, useTransition, type FormEvent, type ReactNode } from 'react';
import { Check, KeyRound, Plus, ShieldCheck, ShieldOff, X } from 'lucide-react';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { ACCESS_MODULES, ACCESS_MODULE_META, type AccessModule } from '@/lib/staff-portal/access-modules';
import { DEPARTMENT_META, STAFF_DEPARTMENTS, type StaffDepartment } from '@/lib/staff-portal/constants';
import type { StaffAccessType, StaffPortalAccount } from '@/lib/staff-portal/types';
import { createStaffAccessAction, resetStaffAccessPasswordAction, setStaffAccessActiveAction, setStaffAccessModuleAction } from '@/app/staff-access/actions';

const fieldClass = 'h-10 w-full rounded-lg border border-input bg-white px-3 text-sm outline-none transition focus:border-ring focus:ring-2 focus:ring-ring/20';

export function StaffAccessPanel({ staffMembers, initialAccounts }: { staffMembers: { id: number; name: string }[]; initialAccounts: StaffPortalAccount[] }) {
  const [accounts, setAccounts] = useState(initialAccounts);
  const [department, setDepartment] = useState<StaffDepartment>('booking');
  const [creating, setCreating] = useState<StaffAccessType | null>(null);
  const [managing, setManaging] = useState<StaffPortalAccount | null>(null);
  const [resetting, setResetting] = useState<StaffPortalAccount | null>(null);
  const [pending, startTransition] = useTransition();
  const visible = useMemo(() => accounts.filter((item) => item.departments.some((grant) => grant.active && grant.department === department)), [accounts, department]);

  function toggleActive(account: StaffPortalAccount) {
    startTransition(async () => {
      await setStaffAccessActiveAction(account.id, !account.active);
      setAccounts((rows) => rows.map((row) => row.id === account.id ? { ...row, active: !row.active } : row));
    });
  }

  return <div className="space-y-6">
    <div><p className="text-sm font-medium text-primary">People & access</p><h1 className="mt-1 text-2xl font-semibold tracking-[-0.03em]">Staff Access</h1><p className="mt-1 text-sm text-muted-foreground">Create department Main IDs and quote-only Staff IDs from one secure workspace.</p></div>
    <div className="grid gap-5 xl:grid-cols-[280px_minmax(0,1fr)]">
      <Card className="gap-0 border-border py-0 shadow-level-1 ring-0"><CardHeader className="border-b bg-[#fcfaf7] px-4 py-4"><CardTitle className="text-base">Departments</CardTitle></CardHeader><CardContent className="space-y-1 p-3">
        {STAFF_DEPARTMENTS.map((item) => { const count = accounts.filter((account) => account.departments.some((grant) => grant.active && grant.department === item)).length; return <button key={item} type="button" onClick={() => setDepartment(item)} className={`flex w-full items-center justify-between rounded-lg border px-3 py-2.5 text-left text-sm transition ${department === item ? 'border-[#e4d2b6] bg-[#f5ead8] font-semibold text-[#70481c]' : 'border-transparent hover:bg-[#f7f4ef]'}`}><span>{DEPARTMENT_META[item].label}</span><Badge variant="outline" className="bg-white">{count}</Badge></button>; })}
      </CardContent></Card>
      <Card className="gap-0 overflow-hidden border-border py-0 shadow-level-1 ring-0"><CardHeader className="border-b bg-[#fcfaf7] px-5 py-4"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><CardTitle>{DEPARTMENT_META[department].label} Department</CardTitle><p className="mt-1 text-xs text-muted-foreground">Main IDs receive selected modules. Staff IDs can only prepare quotations.</p></div><div className="flex gap-2"><Button variant="outline" size="sm" onClick={() => setCreating('main')}><Plus/>Create Main ID</Button>{department === 'booking' ? <Button size="sm" onClick={() => setCreating('staff')}><Plus/>Create Staff ID</Button> : null}</div></div></CardHeader>
        <CardContent className="p-0">{visible.length ? <div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left text-sm"><thead className="border-b bg-[#f7f4ef] text-xs text-muted-foreground"><tr><th className="px-5 py-3">Name / Login ID</th><th className="px-5 py-3">Type</th><th className="px-5 py-3">Access</th><th className="px-5 py-3">Status</th><th className="px-5 py-3 text-right">Actions</th></tr></thead><tbody>{visible.map((account) => <tr key={account.id} className="border-b last:border-0"><td className="px-5 py-4"><strong className="block">{account.name}</strong><span className="text-xs text-muted-foreground">{account.loginId}</span></td><td className="px-5 py-4"><Badge variant="outline">{account.accessType === 'main' ? 'Main ID' : 'Staff ID'}</Badge></td><td className="px-5 py-4 text-muted-foreground">{account.accessType === 'staff' ? 'Create quotations only' : `${account.modules.length} selected modules`}</td><td className="px-5 py-4"><Badge variant="outline" className={account.active ? 'border-emerald-200 bg-emerald-50 text-emerald-700' : ''}>{account.active ? 'Active' : 'Disabled'}</Badge></td><td className="px-5 py-4"><div className="flex justify-end gap-2">{account.accessType === 'main' ? <Button size="sm" variant="outline" onClick={() => setManaging(account)}><ShieldCheck/>Manage access</Button> : null}<Button size="sm" variant="outline" onClick={() => setResetting(account)}><KeyRound/>Password</Button><Button size="sm" variant="ghost" disabled={pending} onClick={() => toggleActive(account)}>{account.active ? <ShieldOff/> : <ShieldCheck/>}{account.active ? 'Disable' : 'Enable'}</Button></div></td></tr>)}</tbody></table></div> : <div className="grid min-h-52 place-items-center p-8 text-center text-sm text-muted-foreground">No IDs have been created for this department.</div>}</CardContent>
      </Card>
    </div>
    {creating ? <CreateDialog type={creating} department={department} staffMembers={staffMembers} onClose={() => setCreating(null)} onCreated={(account) => { setAccounts((rows) => [account, ...rows]); setCreating(null); }} /> : null}
    {managing ? <ManageDialog account={managing} onClose={() => setManaging(null)} onChange={(module, enabled) => { setAccounts((rows) => rows.map((row) => row.id === managing.id ? { ...row, modules: enabled ? [...new Set([...row.modules, module])] : row.modules.filter((item) => item !== module) } : row)); setManaging((row) => row ? { ...row, modules: enabled ? [...new Set([...row.modules, module])] : row.modules.filter((item) => item !== module) } : null); }} /> : null}
    {resetting ? <PasswordDialog account={resetting} onClose={() => setResetting(null)} /> : null}
  </div>;
}

function Modal({ title, subtitle, onClose, children }: { title: string; subtitle: string; onClose: () => void; children: ReactNode }) { return <div className="fixed inset-0 z-[70] grid place-items-center bg-[#211d18]/70 p-4 backdrop-blur-sm"><dialog open className="m-0 max-h-[90dvh] w-full max-w-xl overflow-y-auto rounded-[22px] border border-white/40 bg-[#fffdf9] p-0 text-foreground shadow-[0_32px_90px_rgb(20_15_10_/.35)]"><div className="flex justify-between border-b bg-[#fcfaf7] px-5 py-5"><div><h2 className="text-lg font-semibold">{title}</h2><p className="mt-1 text-xs text-muted-foreground">{subtitle}</p></div><button type="button" aria-label="Close" onClick={onClose} className="grid size-9 place-items-center rounded-full border bg-white"><X className="size-4"/></button></div>{children}</dialog></div>; }

function CreateDialog({ type, department, staffMembers, onClose, onCreated }: { type: StaffAccessType; department: StaffDepartment; staffMembers: { id: number; name: string }[]; onClose: () => void; onCreated: (account: StaffPortalAccount) => void }) {
  const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const [modules, setModules] = useState<AccessModule[]>(type === 'staff' ? ['quotations', 'create_booking'] : []);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); const password = String(form.get('password') ?? ''); if (password.length < 6) { setError('Password must be at least 6 characters.'); return; } setBusy(true); const linked = staffMembers.find((item) => String(item.id) === String(form.get('staffMemberId') ?? '')); const result = await createStaffAccessAction({ staffMemberId: linked?.id ?? null, name: String(form.get('name') ?? '').trim() || linked?.name || '', loginId: String(form.get('loginId') ?? '').trim(), password, department, accessType: type, modules }); setBusy(false); if (result.error || !result.account) { setError(result.error ?? 'Could not create this ID.'); return; } onCreated(result.account); }
  return <Modal title={`Create ${type === 'main' ? 'Main ID' : 'Staff ID'}`} subtitle={type === 'staff' ? 'This login can prepare and save quotations only.' : `Choose the modules this ${DEPARTMENT_META[department].label} ID can use.`} onClose={onClose}><form onSubmit={submit} className="space-y-4 p-5"><label className="block text-sm"><span className="font-medium">Link staff record (optional)</span><select name="staffMemberId" className={`mt-1.5 ${fieldClass}`}><option value="">Not linked</option>{staffMembers.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label className="block text-sm"><span className="font-medium">Display name</span><input name="name" required className={`mt-1.5 ${fieldClass}`}/></label><label className="block text-sm"><span className="font-medium">Login ID</span><input name="loginId" required className={`mt-1.5 ${fieldClass}`}/></label><label className="block text-sm"><span className="font-medium">Temporary password</span><input name="password" type="password" required minLength={6} className={`mt-1.5 ${fieldClass}`}/></label>{type === 'main' ? <div><p className="text-sm font-medium">Module access</p><div className="mt-2 grid gap-2 sm:grid-cols-2">{ACCESS_MODULES.map((module) => <label key={module} className="flex gap-2 rounded-lg border p-3 text-sm"><input type="checkbox" checked={modules.includes(module)} onChange={(event) => setModules((rows) => event.target.checked ? [...rows, module] : rows.filter((item) => item !== module))}/><span><strong className="block">{ACCESS_MODULE_META[module].label}</strong><span className="text-xs text-muted-foreground">{ACCESS_MODULE_META[module].description}</span></span></label>)}</div></div> : <div className="rounded-xl border border-[#e4d2b6] bg-[#f5ead8] p-4 text-sm text-[#70481c]"><strong>Fixed quote-only access</strong><p className="mt-1">Payment fields are locked and Create Order is unavailable.</p></div>}{error ? <p className="text-sm text-destructive">{error}</p> : null}<div className="flex justify-end gap-2 border-t pt-4"><Button type="button" variant="outline" onClick={onClose}>Cancel</Button><Button disabled={busy}><Check/>{busy ? 'Creating…' : 'Create ID'}</Button></div></form></Modal>;
}

function ManageDialog({ account, onClose, onChange }: { account: StaffPortalAccount; onClose: () => void; onChange: (module: AccessModule, enabled: boolean) => void }) { const [pending, startTransition] = useTransition(); return <Modal title={`Manage access · ${account.name}`} subtitle="Only enabled modules will appear after this Main ID signs in." onClose={onClose}><div className="grid gap-2 p-5 sm:grid-cols-2">{ACCESS_MODULES.map((module) => { const enabled = account.modules.includes(module); return <label key={module} className="flex items-start justify-between gap-3 rounded-lg border p-3"><span><strong className="block text-sm">{ACCESS_MODULE_META[module].label}</strong><span className="text-xs text-muted-foreground">{ACCESS_MODULE_META[module].description}</span></span><input type="checkbox" checked={enabled} disabled={pending} onChange={(event) => { const next = event.target.checked; startTransition(async () => { await setStaffAccessModuleAction(account.id, module, next); onChange(module, next); }); }}/></label>; })}</div></Modal>; }

function PasswordDialog({ account, onClose }: { account: StaffPortalAccount; onClose: () => void }) { const [busy, setBusy] = useState(false); const [error, setError] = useState(''); async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const password = String(new FormData(event.currentTarget).get('password') ?? ''); if (password.length < 6) { setError('Password must be at least 6 characters.'); return; } setBusy(true); await resetStaffAccessPasswordAction(account.id, password); setBusy(false); onClose(); } return <Modal title={`Reset password · ${account.name}`} subtitle="The existing password is never displayed." onClose={onClose}><form onSubmit={submit} className="space-y-4 p-5"><input name="password" type="password" required minLength={6} placeholder="New password" className={fieldClass}/>{error ? <p className="text-sm text-destructive">{error}</p> : null}<div className="flex justify-end gap-2"><Button type="button" variant="outline" onClick={onClose}>Cancel</Button><Button disabled={busy}><Check/>{busy ? 'Saving…' : 'Save password'}</Button></div></form></Modal>; }
