create table if not exists public.laundry_batches (
  id bigint generated by default as identity primary key,
  owner_id uuid not null references auth.users(id) on delete cascade,
  batch_number text not null,
  vendor_id bigint not null references public.vendors(id),
  status text not null default 'in_progress' check (status in ('in_progress','returned','cancelled')),
  sent_date date not null default current_date,
  expected_return_date date not null,
  total_cost numeric(12,2) not null default 0 check (total_cost >= 0),
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(owner_id, batch_number)
);

create table if not exists public.laundry_batch_items (
  id bigint generated by default as identity primary key,
  batch_id bigint not null references public.laundry_batches(id) on delete cascade,
  product_id bigint references public.products(id) on delete set null,
  product_name text not null,
  quantity integer not null default 1 check (quantity > 0),
  condition_before text not null default 'dirty',
  condition_after text,
  unit_cost numeric(12,2) not null default 0 check (unit_cost >= 0),
  notes text,
  created_at timestamptz not null default now()
);

create table if not exists public.laundry_batch_notes (
  id bigint generated by default as identity primary key,
  batch_id bigint not null references public.laundry_batches(id) on delete cascade,
  owner_id uuid not null references auth.users(id) on delete cascade,
  note text not null,
  created_at timestamptz not null default now()
);

create index if not exists laundry_batches_owner_status_idx on public.laundry_batches(owner_id, status, sent_date desc);
create index if not exists laundry_batch_items_batch_idx on public.laundry_batch_items(batch_id);
create index if not exists laundry_batch_notes_batch_idx on public.laundry_batch_notes(batch_id, created_at desc);

alter table public.laundry_batches enable row level security;
alter table public.laundry_batch_items enable row level security;
alter table public.laundry_batch_notes enable row level security;
drop policy if exists laundry_batches_owner on public.laundry_batches;
drop policy if exists laundry_batch_items_owner on public.laundry_batch_items;
drop policy if exists laundry_batch_notes_owner on public.laundry_batch_notes;
create policy laundry_batches_owner on public.laundry_batches for all to authenticated using (owner_id = (select auth.uid())) with check (owner_id = (select auth.uid()));
create policy laundry_batch_items_owner on public.laundry_batch_items for all to authenticated using (exists (select 1 from public.laundry_batches b where b.id = batch_id and b.owner_id = (select auth.uid()))) with check (exists (select 1 from public.laundry_batches b where b.id = batch_id and b.owner_id = (select auth.uid())));
create policy laundry_batch_notes_owner on public.laundry_batch_notes for all to authenticated using (owner_id = (select auth.uid())) with check (owner_id = (select auth.uid()));
grant select, insert, update, delete on public.laundry_batches, public.laundry_batch_items, public.laundry_batch_notes to authenticated;
grant usage, select on all sequences in schema public to authenticated;
