-- Replace the abandoned hierarchical permission experiment with the minimal Staff Access model.
-- Business records and existing staff/auth accounts are preserved.
begin;

drop function if exists public.assign_department_main(text,bigint,text);
drop function if exists public.set_department_main_active(uuid,boolean);
drop function if exists public.set_main_module_permission(uuid,text,boolean);
drop function if exists public.assign_staff_to_department_main(uuid,bigint);
drop function if exists public.set_staff_module_permission(bigint,text,boolean);
drop function if exists public.staff_has_any_module(text[]) cascade;
drop function if exists public.staff_has_module(text) cascade;
drop function if exists public.permission_allowed_for_department(text,text) cascade;
drop table if exists public.permission_activity_log;
drop table if exists public.staff_module_permissions;
drop table if exists public.department_main_ids;
drop table if exists public.department_staff_assignments;

alter table public.staff_members add column if not exists access_type text not null default 'staff';
alter table public.staff_members drop constraint if exists staff_members_access_type_check;
alter table public.staff_members add constraint staff_members_access_type_check check (access_type in ('main','staff'));

create table if not exists public.staff_access_modules (
  id bigint generated by default as identity primary key,
  owner_id uuid not null references public.profiles(id) on delete cascade,
  staff_id bigint not null references public.staff_members(id) on delete cascade,
  module text not null check (module in ('dashboard','bookings','quotations','create_booking','calendar','event_jobs','stylist_approvals','travel','performance','modifications','inventory','packages','customers','ledger')),
  enabled boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(staff_id,module)
);
create index if not exists staff_access_modules_owner_idx on public.staff_access_modules(owner_id,staff_id);
alter table public.staff_access_modules enable row level security;

create or replace function public.current_staff_member_id()
returns bigint language sql stable security definer set search_path='' as $$
  select id from public.staff_members where user_id=(select auth.uid()) and portal_active and is_active limit 1
$$;

drop policy if exists staff_access_modules_owner_all on public.staff_access_modules;
create policy staff_access_modules_owner_all on public.staff_access_modules for all to authenticated
  using (owner_id=(select auth.uid())) with check (owner_id=(select auth.uid()));
drop policy if exists staff_access_modules_self_select on public.staff_access_modules;
create policy staff_access_modules_self_select on public.staff_access_modules for select to authenticated
  using (staff_id=public.current_staff_member_id());

create or replace function public.staff_can_access(requested_module text)
returns boolean language sql stable security definer set search_path='' as $$
  select exists(
    select 1 from public.staff_members sm
    where sm.user_id=(select auth.uid()) and sm.portal_active and sm.is_active
      and ((sm.access_type='staff' and requested_module in ('quotations','create_booking'))
        or (sm.access_type='main' and exists(
          select 1 from public.staff_access_modules sam where sam.staff_id=sm.id and sam.owner_id=sm.owner_id
            and sam.module=requested_module and sam.enabled)))
  )
$$;

create or replace function public.staff_can_access_any(requested_modules text[])
returns boolean language sql stable security definer set search_path='' as $$
  select exists(select 1 from unnest(requested_modules) module where public.staff_can_access(module))
$$;

create or replace function public.current_booking_owner()
returns uuid language sql stable security definer set search_path='' as $$
  select case when p.role='admin' then p.id
    when p.role='staff' and (public.staff_can_access('quotations') or public.staff_can_access('bookings') or public.staff_can_access('create_booking'))
      then public.current_staff_owner() else null end
  from public.profiles p where p.id=(select auth.uid()) limit 1
$$;

create or replace function public.enforce_quote_only_staff()
returns trigger language plpgsql security definer set search_path='' as $$
declare account_type text;
begin
  select sm.access_type into account_type from public.staff_members sm
  where sm.user_id=(select auth.uid()) and sm.portal_active and sm.is_active limit 1;
  if account_type='staff' then
    if new.is_quote is not true then raise exception 'Staff IDs can save quotations only'; end if;
    if coalesce(new.paid_amount,0) <> 0 or coalesce(new.discount,0) <> 0 then
      raise exception 'Staff IDs cannot edit payment or discount details';
    end if;
  end if;
  return new;
end
$$;
drop trigger if exists enforce_quote_only_staff_trigger on public.bookings;
create trigger enforce_quote_only_staff_trigger before insert or update on public.bookings
for each row execute function public.enforce_quote_only_staff();

create or replace function public.block_staff_payment_writes()
returns trigger language plpgsql security definer set search_path='' as $$
begin
  if exists(select 1 from public.staff_members sm where sm.user_id=(select auth.uid()) and sm.access_type='staff') then
    raise exception 'Staff IDs cannot record payments';
  end if;
  return new;
end
$$;
drop trigger if exists block_staff_payment_writes_trigger on public.booking_payments;
create trigger block_staff_payment_writes_trigger before insert or update or delete on public.booking_payments
for each row execute function public.block_staff_payment_writes();

drop policy if exists bookings_staff_select on public.bookings;
drop policy if exists bookings_booking_staff_insert on public.bookings;
drop policy if exists bookings_booking_staff_update on public.bookings;
create policy bookings_staff_select on public.bookings for select to authenticated using (owner_id=public.current_staff_owner() and ((is_quote and public.staff_can_access('quotations')) or (not is_quote and public.staff_can_access('bookings'))));
create policy bookings_booking_staff_insert on public.bookings for insert to authenticated with check (owner_id=public.current_staff_owner() and ((is_quote and public.staff_can_access('quotations')) or (not is_quote and public.staff_can_access('bookings'))));
create policy bookings_booking_staff_update on public.bookings for update to authenticated using (owner_id=public.current_staff_owner() and ((is_quote and public.staff_can_access('quotations')) or (not is_quote and public.staff_can_access('bookings')))) with check (owner_id=public.current_staff_owner() and ((is_quote and public.staff_can_access('quotations')) or (not is_quote and public.staff_can_access('bookings'))));

drop policy if exists customers_staff_select on public.customers;
drop policy if exists customers_booking_staff_insert on public.customers;
drop policy if exists customers_booking_staff_update on public.customers;
create policy customers_staff_select on public.customers for select to authenticated using (owner_id=public.current_staff_owner() and public.staff_can_access_any(array['customers','quotations','bookings','create_booking']));
create policy customers_booking_staff_insert on public.customers for insert to authenticated with check (owner_id=public.current_staff_owner() and public.staff_can_access_any(array['customers','quotations','bookings','create_booking']));
create policy customers_booking_staff_update on public.customers for update to authenticated using (owner_id=public.current_staff_owner() and public.staff_can_access_any(array['customers','quotations','bookings','create_booking'])) with check (owner_id=public.current_staff_owner() and public.staff_can_access_any(array['customers','quotations','bookings','create_booking']));

drop policy if exists staff_members_booking_staff_select on public.staff_members;
create policy staff_members_booking_staff_select on public.staff_members for select to authenticated using (owner_id=public.current_staff_owner());
drop policy if exists products_booking_staff_select on public.products;
create policy products_booking_staff_select on public.products for select to authenticated using (owner_id=public.current_staff_owner() and public.staff_can_access_any(array['inventory','quotations','bookings','create_booking']));
drop policy if exists product_variants_booking_staff_select on public.product_variants;
create policy product_variants_booking_staff_select on public.product_variants for select to authenticated using (owner_id=public.current_staff_owner() and public.staff_can_access_any(array['inventory','quotations','bookings','create_booking']));
drop policy if exists packages_booking_staff_select on public.packages;
create policy packages_booking_staff_select on public.packages for select to authenticated using (owner_id=public.current_staff_owner() and public.staff_can_access_any(array['packages','quotations','bookings','create_booking']));
drop policy if exists package_items_booking_staff_select on public.package_items;
create policy package_items_booking_staff_select on public.package_items for select to authenticated using (owner_id=public.current_staff_owner() and public.staff_can_access_any(array['packages','quotations','bookings','create_booking']));
drop policy if exists package_categories_booking_staff_select on public.package_categories;
create policy package_categories_booking_staff_select on public.package_categories for select to authenticated using (owner_id=public.current_staff_owner() and public.staff_can_access_any(array['packages','quotations','bookings','create_booking']));
drop policy if exists package_variants_booking_staff_select on public.package_variants;
create policy package_variants_booking_staff_select on public.package_variants for select to authenticated using (owner_id=public.current_staff_owner() and public.staff_can_access_any(array['packages','quotations','bookings','create_booking']));

drop policy if exists booking_items_staff_select on public.booking_items;
drop policy if exists booking_items_booking_staff_insert on public.booking_items;
drop policy if exists booking_items_booking_staff_update on public.booking_items;
drop policy if exists booking_items_booking_staff_delete on public.booking_items;
create policy booking_items_staff_select on public.booking_items for select to authenticated using (owner_id=public.current_staff_owner() and exists(select 1 from public.bookings b where b.id=booking_id and ((b.is_quote and public.staff_can_access('quotations')) or (not b.is_quote and public.staff_can_access('bookings')))));
create policy booking_items_booking_staff_insert on public.booking_items for insert to authenticated with check (owner_id=public.current_staff_owner() and exists(select 1 from public.bookings b where b.id=booking_id and ((b.is_quote and public.staff_can_access('quotations')) or (not b.is_quote and public.staff_can_access('bookings')))));
create policy booking_items_booking_staff_update on public.booking_items for update to authenticated using (owner_id=public.current_staff_owner() and exists(select 1 from public.bookings b where b.id=booking_id and ((b.is_quote and public.staff_can_access('quotations')) or (not b.is_quote and public.staff_can_access('bookings'))))) with check (owner_id=public.current_staff_owner());
create policy booking_items_booking_staff_delete on public.booking_items for delete to authenticated using (owner_id=public.current_staff_owner() and exists(select 1 from public.bookings b where b.id=booking_id and ((b.is_quote and public.staff_can_access('quotations')) or (not b.is_quote and public.staff_can_access('bookings')))));

drop policy if exists booking_payments_booking_staff_select on public.booking_payments;
drop policy if exists booking_payments_booking_staff_insert on public.booking_payments;
create policy booking_payments_booking_staff_select on public.booking_payments for select to authenticated using (owner_id=public.current_staff_owner() and public.staff_can_access('bookings'));
create policy booking_payments_booking_staff_insert on public.booking_payments for insert to authenticated with check (owner_id=public.current_staff_owner() and public.staff_can_access('bookings'));
drop policy if exists event_jobs_staff_select on public.event_jobs;
create policy event_jobs_staff_select on public.event_jobs for select to authenticated using (owner_id=public.current_staff_owner() and public.staff_can_access('event_jobs'));

-- Preserve legacy department logins as Main IDs and legacy STAFF-01 style logins as quote-only Staff IDs.
update public.staff_members
set access_type=case when lower(coalesce(login_id,'')) like 'staff-%' then 'staff' else 'main' end
where user_id is not null;

commit;
